name: Create release for next class

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  createRelease:
    name: Generate test data and convert md files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: mkdir ${{ github.workspace }}/Release/Aufgaben -p && mkdir ${{ github.workspace }}/Release/Testdaten
      - run: cp -R ${{ github.workspace }}/Beispielkonfigurationen ${{ github.workspace }}/Release/
      - name: generate Documents
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Aufgaben
          output_dir: Release/Aufgaben/
          build_pdf: false
      - uses: vimtor/action-zip@v1.2
        with:
          files: Release/
          recursive: 'true'
          dest: release.zip
      - uses: actions/upload-artifact@v4
        with:
          name: release.zip
          path: ${{ github.workspace }}/release.zip
      - uses: actions/upload-artifact@v4
        with:
          name: docker-setup.sh
          path: ${{ github.workspace }}/Skripte/docker-setup.sh
      - uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 1
          keep-old-minor-releases: false
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip,docker-setup.sh"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          body: Dieser Release enthält den aktuellsten Stand der Testdaten und Übungsaufgaben.